image: Visual Studio 2015

skip_branch_with_pr: true

environment:
  matrix:
    -  PYTHON: "C:\\Python37-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.13.0
       QT_BASE_PATH: c:\\Qt\\5.13.0
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    -  PYTHON: "C:\\Python37"
       PYQT5_VERSION: 5.13.0
       QT_BASE_PATH: c:\\Qt\\5.13.0
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    -  PYTHON: "C:\\Python36-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.13.0
       QT_BASE_PATH: c:\\Qt\\5.13.0

    -  PYTHON: "C:\\Python36"
       PYQT5_VERSION: 5.13.0
       QT_BASE_PATH: c:\\Qt\\5.13.0
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    -  PYTHON: "C:\\python35-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.13.0
       QT_BASE_PATH: c:\\Qt\\5.13.0

    -  PYTHON: "C:\\python35"
       PYQT5_VERSION: 5.13.0
       QT_BASE_PATH: c:\\Qt\\5.13.0
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    -  PYTHON: "C:\\Python37-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.12.3
       QT_BASE_PATH: c:\\Qt\\5.12.4
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    -  PYTHON: "C:\\Python37"
       PYQT5_VERSION: 5.12.3
       QT_BASE_PATH: c:\\Qt\\5.12.4
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    -  PYTHON: "C:\\Python36-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.12.3
       QT_BASE_PATH: c:\\Qt\\5.12.4

    -  PYTHON: "C:\\Python36"
       PYQT5_VERSION: 5.12.3
       QT_BASE_PATH: c:\\Qt\\5.12.4
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    -  PYTHON: "C:\\python35-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.12.3
       QT_BASE_PATH: c:\\Qt\\5.12.4

    -  PYTHON: "C:\\python35"
       PYQT5_VERSION: 5.12.3
       QT_BASE_PATH: c:\\Qt\\5.12.4
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    -  PYTHON: "C:\\Python37-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.11.3
       QT_BASE_PATH: c:\\Qt\\5.11.2
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    -  PYTHON: "C:\\Python37"
       PYQT5_VERSION: 5.11.3
       QT_BASE_PATH: c:\\Qt\\5.11.2

    -  PYTHON: "C:\\Python36-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.11.3
       QT_BASE_PATH: c:\\Qt\\5.11.2

    -  PYTHON: "C:\\Python36"
       PYQT5_VERSION: 5.11.3
       QT_BASE_PATH: c:\\Qt\\5.11.2

    -  PYTHON: "C:\\python35-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.11.3
       QT_BASE_PATH: c:\\Qt\\5.11.2

    -  PYTHON: "C:\\python35"
       PYQT5_VERSION: 5.11.3
       QT_BASE_PATH: c:\\Qt\\5.11.2

    -  PYTHON: "C:\\Python37-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.10.1
       QT_BASE_PATH: c:\\Qt\\5.10.1
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    -  PYTHON: "C:\\Python37"
       PYQT5_VERSION: 5.10.1
       QT_BASE_PATH: c:\\Qt\\5.10.1
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    -  PYTHON: "C:\\Python36-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.10.1
       QT_BASE_PATH: c:\\Qt\\5.10.1
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    -  PYTHON: "C:\\Python36"
       PYQT5_VERSION: 5.10.1
       QT_BASE_PATH: c:\\Qt\\5.10.1
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    -  PYTHON: "C:\\python35-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.10.1
       QT_BASE_PATH: c:\\Qt\\5.10.1
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    -  PYTHON: "C:\\python35"
       PYQT5_VERSION: 5.10.1
       QT_BASE_PATH: c:\\Qt\\5.10.1
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

#    -  PYTHON: "C:\\Python37-x64"
#       PYTHON_SUFFIX: "-x64"
#       PYQT5_VERSION: 5.9.2
#       QT_BASE_PATH: c:\\Qt\\5.9.7
#       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#
#    -  PYTHON: "C:\\Python37"
#       PYQT5_VERSION: 5.9.2
#       QT_BASE_PATH: c:\\Qt\\5.9.7
#
#    -  PYTHON: "C:\\Python36-x64"
#       PYTHON_SUFFIX: "-x64"
#       PYQT5_VERSION: 5.9.2
#       QT_BASE_PATH: c:\\Qt\\5.9.7
#
#    -  PYTHON: "C:\\Python36"
#       PYQT5_VERSION: 5.9.2
#       QT_BASE_PATH: c:\\Qt\\5.9.7
#
#    -  PYTHON: "C:\\python35-x64"
#       PYTHON_SUFFIX: "-x64"
#       PYQT5_VERSION: 5.9.2
#       QT_BASE_PATH: c:\\Qt\\5.9.7
#
#    -  PYTHON: "C:\\python35"
#       PYQT5_VERSION: 5.9.2
#       QT_BASE_PATH: c:\\Qt\\5.9.7



# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
init:
  - ps: if (Get-ChildItem Env:ENABLE_RDP -ErrorAction SilentlyContinue) {iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}

build_script:
  - "%PYTHON%%\\python -m venv venv"
  - "venv\\scripts\\python -m pip freeze"
  - "venv\\scripts\\python stderr.py"
  - "venv\\scripts\\python -m pip install --upgrade pip"
  - "venv\\scripts\\python -m pip install requests==2.13.0"
  - "venv\\scripts\\python -m pip install vcversioner==2.16.0.0"
  - "venv\\scripts\\python -m pip install wheel==0.30.0a0"
  - "venv\\scripts\\python -m pip install twine==1.11.0"
  - "venv\\scripts\\python -m pip freeze"
  - "venv\\scripts\\python setup.py bdist_wheel"
  - "copy dist\\*.whl ."
  - ps: Get-ChildItem .\*.whl | % { Push-AppveyorArtifact $_.FullName }
  - "venv\\scripts\\python twineontag.py"

test_script:
  - "%PYTHON%%\\python -m venv venv-test"
  - "venv-test\\scripts\\python -m pip install --upgrade pip"
  - "venv-test\\scripts\\python -m pip install pytest==3.9.1"
  - "venv-test\\scripts\\python -m pip install pyqt5==%PYQT5_VERSION%"
  - ps: "venv-test\\scripts\\python -m pip install --no-warn-script-location (get-item dist\\*.whl).FullName"
  - "venv-test\\scripts\\python -m pip freeze"
  - "venv-test\\scripts\\python -m pytest pyqt5_tools.tests --pyargs"

artifacts:
  - path: '*.whl'

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
on_finish:
  - ps: if (Get-ChildItem Env:ENABLE_RDP -ErrorAction SilentlyContinue) {$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}
