image: Visual Studio 2017

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci\\run_with_env.cmd"

  matrix:
    -  PYTHON: "C:\\Python37-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.11.2
       QT_BASE_PATH: c:\\Qt\\5.11

    -  PYTHON: "C:\\Python37-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.10.1
       QT_BASE_PATH: c:\\Qt\\5.10

    -  PYTHON: "C:\\Python37-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.9.2
       QT_BASE_PATH: c:\\Qt\\5.9

    -  PYTHON: "C:\\Python36"
       PYQT5_VERSION: 5.11.2
       QT_BASE_PATH: c:\\Qt\\5.11

    -  PYTHON: "C:\\Python36"
       PYQT5_VERSION: 5.10.1
       QT_BASE_PATH: c:\\Qt\\5.10

    -  PYTHON: "C:\\Python36"
       PYQT5_VERSION: 5.9.2
       QT_BASE_PATH: c:\\Qt\\5.9

    -  PYTHON: "C:\\python35"
       PYQT5_VERSION: 5.11.2
       QT_BASE_PATH: c:\\Qt\\5.11

    -  PYTHON: "C:\\python35"
       PYQT5_VERSION: 5.10.1
       QT_BASE_PATH: c:\\Qt\\5.10

    -  PYTHON: "C:\\python35"
       PYQT5_VERSION: 5.9.2
       QT_BASE_PATH: c:\\Qt\\5.9


# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
init:
  - ps: if (Get-ChildItem Env:ENABLE_RDP -ErrorAction SilentlyContinue) {iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}

build_script:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - "python -m pip freeze"
  # Build the compiled extension
  - "python stderr.py"
  - "pip install requests==2.13.0"
  - "pip install vcversioner==2.16.0.0"
  - "pip install wheel==0.30.0a0"
  - "python -m pip freeze"
  - "python setup.py bdist_wheel"
  - "copy dist\\*.whl ."

artifacts:
  - path: '*.whl'

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
on_finish:
  - ps: if (Get-ChildItem Env:ENABLE_RDP -ErrorAction SilentlyContinue) {$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}
