[build-system]
requires = [
    "attrs",
    "aqtinstall==0.7.5",
    "py7zr==0.6b6",
    "hyperlink",
    "macholib",
    "psutil",
    "pylddwrap",
    "PyQt-builder",
    "requests",
    "setuptools",
    "sip",
    "vcversioner",
    "wheel",
]
