[build-system]
requires = [
    "attrs",
    "aqtinstall==0.8a3",
    "py7zr==0.6b6",
    "importlib-metadata",
    "hyperlink",
    "macholib",
    "psutil",
    "pylddwrap",
    "PyQt-builder==1.3.1",
    "requests",
    "setuptools==46.1.3.",
    "sip==5.2.0",
    "vcversioner",
    "wheel",
]
