name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.os.image }}
    strategy:
      matrix:
        system:
          - image: windows-2019
            platform: windows
            aqt_name: win64_msvc2017_64
            qt_compiler: msvc2017_64
          - image: ubuntu-18.04
            platform: linux
            aqt_name: gcc_64
            qt_compiler: gcc_64
          - image: macos-10.15
            platform: mac
            aqt_name: clang_64
            qt_compiler: clang_64
        versions:
          - qt: 5.14.1
            pyqt: 5.14.1
        python:
          - 3.8

    env:
#      QT_COMPILER_DIRECTORY: ${{ env.QT_BASE_DIRECTORY }}/${{ matrix.qt }}/${{ matrix.arch.directory }}
      QT_VERSION: ${{ matrix.versions.qt }}
      QT_PLATFORM: ${{ matrix.platform }}
      QT_COMPILER: ${{ matrix.system.qt_compiler }}
      QT_ARCHITECTURE: ${{ matrix.system.aqt_name }}
      PYQT_VERSION: ${{ matrix.versions.pyqt }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1
#      - name: Install
#        run: |
#          pip install aqtinstall sip
#          PyQt5==${{ matrix.versions.pyqt }}
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Build wheel
        run: |
          pip wheel .
#      - name: Download
#        run: |
#          venv/bin/pip download --no-deps --no-binary :all: --dest download PyQt5
#      - name: Test
#        run: |
#          tox -v -e "${{ matrix.toxenv }}"
      - name: Archive wheel
        uses: actions/upload-artifact@v1
        with:
          name: pyqt5-tools
          path: dist/pyqt5_tools-*.whl